@JWTAuthorizationInDotNet9_HostAddress = http://localhost:5214

POST {{JWTAuthorizationInDotNet9_HostAddress}}/api/auth/register
Content-Type: application/json


### 2. Login (Get Tokens)
# @name login
POST {{JWTAuthorizationInDotNet9_HostAddress}}/api/auth/login
Content-Type: application/json



###

POST {{JWTAuthorizationInDotNet9_HostAddress}}/api/auth/refresh-token
Content-Type: application/json




###
